name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process Data
        id: process_data
        run: |
          output_file=$(python deep3.py | awk 'END{print $NF}')
          echo "output_file=$output_file" >> $GITHUB_OUTPUT
          echo "Output file: $output_file"  # 输出文件名以供调试

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Check for Changes
        id: check_changes
        run: |
          if git diff --quiet -- "${{ steps.process_data.outputs.output_file }}" ; then
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: steps.check_changes.outputs.changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add "${{ steps.process_data.outputs.output_file }}"
          git commit -m "Update: ${{ steps.process_data.outputs.output_file }} ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push

      - name: Notify of No Changes
        if: steps.check_changes.outputs.changes == 'false'
        run: |
          echo "No changes to commit. The file content is the same as before."
