name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get Output File Name
        id: get_output
        run: |
          FILE_NAME=$(python 3.py | awk 'END{print $NF}')
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT

      - name: Delete existing file
        run: |
          if [ -f "${{ steps.get_output.outputs.file_name }}" ]; then
            rm "${{ steps.get_output.outputs.file_name }}"
            echo "Deleted existing file: ${{ steps.get_output.outputs.file_name }}"
          else
            echo "File does not exist."
          fi
          ls -l  # 列出文件确认

      - name: Process Data
        run: python deep3.py

      - name: Check if file exists after generation
        run: |
          if [ -f "${{ steps.get_output.outputs.file_name }}" ]; then
            echo "File generated successfully: ${{ steps.get_output.outputs.file_name }}"
          else
            echo "File generation failed."
            exit 1
          fi

      - name: Modify file to force change
        run: |
          echo "# Last updated at $(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S')" >> "${{ steps.get_output.outputs.file_name }}"

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add new file
        run: |
          git add -f "${{ steps.get_output.outputs.file_name }}" || echo "Failed to add file: $?"

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git diff --staged
          git commit -m "Update: ${{ steps.get_output.outputs.file_name }} ($(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S'))"
          git push
