name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script and get output file
        run: |
          output_file=$(python deep3.py)
          echo "output_file=$output_file" >> $GITHUB_OUTPUT
        id: run_script

      - name: Debug output file
        run: echo "Output file is: ${{ steps.run_script.outputs.output_file }}"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add and commit output file
        run: |
          git add -f "${{ steps.run_script.outputs.output_file }}"
          git commit -m "Update: ${{ steps.run_script.outputs.output_file }} ($(date '+%Y-%m-%d %H:%M:%S'))" || true
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
