name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Delete existing file
        run: |
          FILE_NAME=$(python deep3.py | awk 'END{print $NF}')
          if [ -f "$FILE_NAME" ]; then
            rm "$FILE_NAME"
            echo "Deleted existing file: $FILE_NAME"
          else
            echo "File does not exist."
          fi

      - name: Process Data
        run: python deep3.py

      - name: Check if file exists after generation
        run: |
          FILE_NAME=$(python deep3.py | awk 'END{print $NF}')
          if [ -f "$FILE_NAME" ]; then
            echo "File generated successfully: $FILE_NAME"
          else
            echo "File generation failed."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Add new file
        run: |
          FILE_NAME=$(python deep3.py | awk 'END{print $NF}')
          git add "$FILE_NAME"

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          FILE_NAME=$(python deep3.py | awk 'END{print $NF}')
          git commit -m "Update: $FILE_NAME ($(date '+%Y-%m-%d %H:%M:%S'))"
          git push
