name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process Data and Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set timezone to Beijing
          export TZ=Asia/Shanghai
          
          # Get the current content of the file
          current_content=$(git show HEAD:path/to/your/output_file)
          
          # Run the script and capture the output content
          new_content=$(python deep3.py)
          
          # Write the new content to a temporary file
          echo "$new_content" > temp_output_file
          
          # Compare the current content with the new content
          if diff <(echo "$current_content") <(echo "$new_content") > /dev/null ; then
            # No changes
            echo "无变化 ($(date '+%Y-%m-%d %H:%M:%S'))"
          else
            # There are changes, commit and push
            # Configure Git
            git config user.name github-actions
            git config user.email github-actions@github.com
            # Stage and commit the new content
            echo "$new_content" > path/to/your/output_file
            git add path/to/your/output_file
            git commit -m "Update: output_file ($(date '+%Y-%m-%d %H:%M:%S'))"
            # Push the changes
            git push
          fi
