name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script and get output file
        run: |
          python deep3.py
          # 假设脚本输出最后一行是文件名
          output_file=$(tail -n 1 deep3.py)
          # 检查文件是否存在
          if [ ! -f "$output_file" ]; then
            echo "Output file $output_file not found."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: run_script

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Add and commit output file
        run: |
          git add -f "${{ steps.run_script.outputs.output_file }}"
          if git diff --staged --exit-code > /dev/null; then
            echo "No changes to commit."
          else
            git commit -m "Update: ${{ steps.run_script.outputs.output_file }} ($(date '+%Y-%m-%d %H:%M:%S'))"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: commit_file

      - name: Push changes
        uses: ad-m/github-push-action@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: ${{ steps.commit_file.outputs.commit }}
        if: steps.commit_file.outputs.commit != ''
