name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process Data
        id: process_data
        run: |
          output_file=$(python deep3.py | awk 'END{print $NF}')
          echo "output_file=$output_file" >> $GITHUB_OUTPUT
          echo "Output file: $output_file"  # 输出文件名以供调试

      - name: Check if file exists
        run: |
          if [ -f "${{ steps.process_data.outputs.output_file }}" ]; then
            echo "File exists."
          else
            echo "File does not exist. Exiting."
            exit 1
          fi

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Commit Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add -f "${{ steps.process_data.outputs.output_file }}"
          git commit -m "Update: ${{ steps.process_data.outputs.output_file }} ($(date '+%Y-%m-%d %H:%M:%S'))" --allow-empty
          git push
