name: Process Live Stream Data

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  process-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Process Data and Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          output_file=$(python 3.py | awk 'END{print $NF}')
          git rm -f "$output_file" || true  # Remove the file from the index
          git add "$output_file"            # Add it back
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Update: $output_file ($(date '+%Y-%m-%d %H:%M:%S'))" || true
          git push
