name: Process Live Stream Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run data processing script
        run: |
          python 1.py

      - name: Commit and push results
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add sorted_live_streams.txt
          git commit -m "Add processed live streams file"
          git push
