name: Process Live Stream Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run data processing script
        run: |
          python 4.py

      - name: Get output file name
        id: get_filename
        run: |
          # 列出当前目录下的所有文件，并找到最新的文件
          # 这里假设最新的文件是修改时间最新的文件
          output_file=$(ls -t | head -1)
          echo "output_file=$output_file" >> $GITHUB_ENV

      - name: Commit and push results
        run: |
          # Configure git user details
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Ensure git is using the token for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

          # Check if the file exists
          if [ -f "${{ env.output_file }}" ]; then
            # Add the processed file
            git add "${{ env.output_file }}"
            git commit -m "Add processed file: ${{ env.output_file }}"
            # Push changes
            git push
          else
            echo "Processed file not found."
            exit 1
          fi
