name: Process Live Stream Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run data processing script
        id: run_script
        run: |
          # 使用 awk 提取最后一行（文件名）
          output_file=$(python 3.py | awk 'END{print $NF}')
          echo "Output file: $output_file"
          echo "output_file=$output_file" >> $GITHUB_OUTPUT

      - name: Commit and push results
        run: |
          # 检查文件是否存在
          if [ -f "${{ steps.run_script.outputs.output_file }}" ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            
            # 添加特定文件
            git add "${{ steps.run_script.outputs.output_file }}"
            
            # 提交更改（只有在有更改时才提交）
            git diff --staged --quiet || git commit -m "Add processed live streams file"
            
            # 推送更改
            git push
          else
            echo "Output file not found"
            exit 1
          fi
