name: Process Live Stream Data

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # 这里启用完整的历史记录，避免浅克隆
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run data processing script
        run: |
          python sjb.py

      - name: Commit and push results
        run: |
          # Configure git user details
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Ensure git is using the token for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          
          # Add the processed file
          git add sjb.m3u
          git commit -m "Add processed live streams file"
          
          # Push changes
          git push
